### PR TITLE
Uarte fix

### PR DESCRIPTION
**Pull request by furbrain**
All recent circuitpython implementations (for the last 4 years) have pointed to commit 3f55e49. 
There is an error in the ``drivers\nrfx_uarte.c`` in the old version that causes the UART peripheral to remain on even after ``uninit``.

There are two commits after this that pull in more recent versions of nrfx, which fixes the above error. However, these do not compile currently against circuitpython 9.0.0, and seem to have been abandoned.

I have created another branch (https://github.com/furbrain/nrfx/tree/v2.1.0-fixes) which fixes the compile time errors however circuitpython hangs shortly after starting up when using this. I've not been able to trace the cause of this.

This pull request does two things

a) revert the current head to 3f55e49
b) just updates the ``uninit`` function in ``nrfx_uarte.c``

This fixes the problem with the UART and is a fairly small change to the *current* codebase. If this PR is accepted we can then change the commit that circuitpython compiles against.

### CODE REVIEW

**Comment by dhalbert** [comment]
I recently started working on updating nrfx to its latest release and updating CircuitPython to match. That work is ongoing in https://github.com/dhalbert/circuitpython/tree/nrfx-update. I also made a new branch in https://github.com/adafruit/nrfx/tree/circuitpython-v3.3.0 which is almost the same as the upstream version, except for two tiny changes to fix compile warnings.

However, I've put the work described above temporarily on hold, because the API changes are significant, and are not that important for 9.0.0. My main goal was to see if there was any fix for https://github.com/adafruit/circuitpython/issues/2253 and if not, to add one in a more recent version.

Instead of reverting `main`, I'll create an new branch for  3f5549, and then you can change the base for this PR to be that. How's that?

**Comment by dhalbert** [comment]
Here is the branch: https://github.com/adafruit/nrfx/tree/circuitpython-v2.0.0.

**Comment by furbrain** [comment]
Yes that's absolutely fine. Mind if I look at that time issue as well -
it's caused me problems previously. I've got a workaround but it's ugly...

Phil

**Comment by dhalbert** [comment]
> Mind if I look at that time issue as well -

Sure. But the driver has changed significantly internally from v2.0.0 to v3.3.0, so I was thinking I would update rather than write it twice.

**Comment by furbrain** [comment]
Closing as done more neatly in #8

**Pull request closed without merging**
